### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [InfinityGamers/GoProxy#1]
Work on Windows 10 Edition?

Btw, hi babe beast my friend :3 

I want show something: https://imgur.com/a/vOyyg1Z

You maked Shop in Database saved, but you don't close database and that make when you use /gc lost all items from shop :p 

And anti cheat is a terrible fault. @xBeastMode 

*I updated anyway and work very good, thanks so much <3*

**Comment by xBeastMode** [comment]
Wtf, who gave you my core? I will report you if anything is leaked.

**Comment by ghost** [comment]
You can't report me lmao. And yeah, it's your core, modificated and very optimised. Thanks anyway. But actually you can't do nothing, you post yourself lmao @xBeastMode

**Comment by xBeastMode** [comment]
I uploaded it to GitHub **PRIVATELY**, do you have proof that I posted it? There was only one person that had it and it wasn't you.

**Comment by ghost** [comment]
That is lmao, you noobish because you posted. Anyway, i have, FULL, with addons by me. I give you a point: Close database when you use transactions because you will got shop empty, because exist gabargage collector. When you have latest version on yaml, yeah, will not be deleted because /gc not affect files .yml, but database affect if it's not closed. And you can got more optimised if you do that.

I don't know if exist on php "try with resources" but i recommand you use them.@xBeastMode

**Comment by ghost** [comment]
And you can't do nothing, anyway if i leaked or not, you can't leak if you can't get from anywhere or anyone. That's your fault, not mine. So, that is. *That's why i love kotlin, because you can't decompile jars kotlin code to kotlin code, haha*

nukkitx the best.

**Comment by samuelctn** [comment]
yeah ac targets more the clean players than the cheaters =)))))))

**Comment by MariusMRN** [comment]
shut up noobish @SamyR0

**Comment by ghost** [comment]
Really beautiful core @xBeastMode https://imgur.com/a/b7ju0is

I invited you to server: play.chpe.us <3

Come here and see what i modified and how best it is now.

Anyway, rainbow it's my creation so please don't "report" me :(

**Comment by samuelctn** [comment]
@MariusMRN LMAO U NOOBISH

**Comment by lukeeey** [comment]
@NycuRO Go fuck yourself you actually fucking piece of shit.
