### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by samuelctn** [InfinityGamers/GoProxy#2]
go build doesnt work
`host.go:5:2: cannot find package "github.com/Irmine/GoMine/net/packets" in any of:
        /usr/lib/go-1.6/src/github.com/Irmine/GoMine/net/packets (from $GOROOT)
        ($GOPATH not set)
root@server11756:~/go/GoProxy# go build client.go
client.go:7:2: cannot find package "github.com/Irmine/GoMine/net/packets" in any of:
        /usr/lib/go-1.6/src/github.com/Irmine/GoMine/net/packets (from $GOROOT)
        ($GOPATH not set)
client.go:9:2: cannot find package "github.com/golang/geo/r3" in any of:
        /usr/lib/go-1.6/src/github.com/golang/geo/r3 (from $GOROOT)
        ($GOPATH not set)
client.go:6:2: cannot find package "github.com/google/uuid" in any of:
        /usr/lib/go-1.6/src/github.com/google/uuid (from $GOROOT)
        ($GOPATH not set)
client.go:5:2: cannot find package "github.com/infinitygamers/mcpeproxy/packets" in any of:
        /usr/lib/go-1.6/src/github.com/infinitygamers/mcpeproxy/packets (from $GOROOT)
        ($GOPATH not set)
root@server11756:~/go/GoProxy# go build
client.go:7:2: cannot find package "github.com/Irmine/GoMine/net/packets" in any of:
        /usr/lib/go-1.6/src/github.com/Irmine/GoMine/net/packets (from $GOROOT)
        ($GOPATH not set)
connection.go:5:2: cannot find package "github.com/Irmine/GoRakLib/protocol" in any of:
        /usr/lib/go-1.6/src/github.com/Irmine/GoRakLib/protocol (from $GOROOT)
        ($GOPATH not set)
client.go:9:2: cannot find package "github.com/golang/geo/r3" in any of:
        /usr/lib/go-1.6/src/github.com/golang/geo/r3 (from $GOROOT)
        ($GOPATH not set)
client.go:6:2: cannot find package "github.com/google/uuid" in any of:
        /usr/lib/go-1.6/src/github.com/google/uuid (from $GOROOT)
        ($GOPATH not set)
default_handlers.go:4:2: cannot find package "github.com/infinitygamers/mcpeproxy/info" in any of:
        /usr/lib/go-1.6/src/github.com/infinitygamers/mcpeproxy/info (from $GOROOT)
        ($GOPATH not set)
client.go:5:2: cannot find package "github.com/infinitygamers/mcpeproxy/packets" in any of:
        /usr/lib/go-1.6/src/github.com/infinitygamers/mcpeproxy/packets (from $GOROOT)
        ($GOPATH not set)
minecraft_batch_packet.go:4:2: cannot find package "github.com/irmine/binutils" in any of:
        /usr/lib/go-1.6/src/github.com/irmine/binutils (from $GOROOT)
        ($GOPATH not set)
config.go:5:2: cannot find package "gopkg.in/yaml.v2" in any of:
        /usr/lib/go-1.6/src/gopkg.in/yaml.v2 (from $GOROOT)
        ($GOPATH not set)
`

**Comment by xBeastMode** [comment]
I think you should search how to setup golang for your OS because I don't know how to help you on this one. Also you're supposed to `go build main.go` in the start folder not `client.go`, you can check the releases for an exe build with cheats.

**Comment by samuelctn** [comment]
ok i solved it anyway thanks
